version: "2.2"
    
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4Ko6my9013!A
      MYSQL_DATABASE: wordpress
      MYSQL_USER: myroot
      MYSQL_PASSWORD: 4Ko6my9013!A
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: myroot
      WORDPRESS_DB_PASSWORD: 4Ko6my9013!A
      WORDPRESS_DB_NAME: wordpress
    volumes: 
       - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini 
volumes:
  db_data: {}